AssetsManager001/AssetsManager001/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('polls/', include('polls.urls',namespace="polls")),
    path('admin/', admin.site.urls),
]

AssetsManager001/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # ホーム
    path('', views.MainView.as_view(), name='main'),
    # 貸出情報一覧
    path('lend/', views.lend, name='lend'),
    path('lend/sort/<int:column_number>/', views.lendSort, name='lendSort'),
    path('lend/delete/', views.lendDelete, name='lendDelete'),
    # 機器一覧
    path('devices/', views.devices, name='devices'),
    path('devices/sort/<int:column_number>/', views.devicesSort, name='devicesSort'),
    path('devices/delete/', views.devicesDelete, name='devicesDelete'),
    # 社員一覧
    path('users/', views.users, name='users'),
    path('users/sort/<int:column_number>/', views.usersSort, name='usersSort'),
    path('users/delete/', views.usersDelete, name='usersDelete'),
    # 貸出情報管理
    path('lend/add/', views.lendAdd, name='lendAdd'),
    path('lend/edit/<int:pk>/', views.lendEdit, name='lendEdit'),
    # 機器情報入力
    path('devices/edit/<int:pk>/', views.devicesEdit, name='devicesEdit'),
    # 社員情報入力
    path('users/edit/<int:pk>/', views.usersEdit, name='usersEdit'),
]

AssetsManager001/polls/models.py
import datetime

from django.db import models
# from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from django.core.validators import MinLengthValidator, RegexValidator
from django.core.exceptions import ValidationError



# 機器情報テーブル
class Devices(models.Model):
    device_id = models.CharField(
        # 管理画面での表示名
        verbose_name="機器番号",
        max_length=30,
        unique=True)
    maker = models.CharField(
        # 管理画面での表示名
        verbose_name="メーカ名",
        max_length=30,
        blank=True,
        null=True)
    OS = models.CharField(
        # 管理画面での表示名
        verbose_name="OS",
        max_length=30,
        blank=True,
        null=True)
    memory = models.CharField(
        # 管理画面での表示名
        verbose_name="メモリ",
        max_length=30,
        blank=True,
        null=True)
    storage = models.CharField(
        # 管理画面での表示名
        verbose_name="容量",
        max_length=30,
        blank=True,
        null=True)
    CPU = models.CharField(
        # 管理画面での表示名
        verbose_name="CPU",
        max_length=30,
        blank=True,
        null=True)
    GPU = models.CharField(
        # 管理画面での表示名
        verbose_name="GPU",
        max_length=30,
        blank=True,
        null=True)
    inventory = models.CharField(
        # 管理画面での表示名
        verbose_name="保管場所",
        max_length=30)
    BROKEN_CHOICES = (
        ("なし","なし"),
        ("あり","あり"),
        )
    broken_flag = models.CharField(
        # 管理画面での表示名
        verbose_name="故障",
        # 初期値
        default="なし",
        max_length=30,
        choices=BROKEN_CHOICES)
    registration_date = models.DateTimeField(
        # 管理画面での表示名
        verbose_name="機器登録日",
        # 初期値
        default=timezone.now())
    remarks = models.TextField(
        # 管理画面での表示名
        verbose_name="備考",
        blank=True,
        null=True)
    delete_flag = models.IntegerField(
        # 管理画面での表示名
        verbose_name="削除フラグ",
        # 初期値
        default=0)
    update_date = models.DateTimeField(
        # モデルインスタンスの度に現在時刻で更新
        auto_now=True)
    def __str__(self):
        return self.device_id

# # 社員情報テーブル
class Users(models.Model):
    user_id = models.IntegerField(
        # 管理画面での表示名
        verbose_name="社員番号",
        max_length=10,
        unique=True)
    name = models.CharField(
        # 管理画面での表示名
        verbose_name="氏名",
        max_length=30)
    age = models.IntegerField(
        # 管理画面での表示名
        verbose_name="年齢",
        max_length=3,
        blank=True,
        null=True)
    GENDER_CHOICES = (
        ("　","無回答"),
        ("男性","男性"),
        ("女性","女性"),
        )
    gender = models.CharField(
        # 管理画面での表示名
        verbose_name="性別",
        max_length=10,
        default="　",
        choices=GENDER_CHOICES)
    tel_number = models.CharField(
        # 管理画面での表示名
        verbose_name="電話番号",
        max_length=20,
        blank=True,
        null=True,
        unique=True)
    mail_address = models.CharField(
        # 管理画面での表示名
        verbose_name="メールアドレス",
        max_length=63,
        blank=True,
        null=True,
        unique=True)
    position = models.CharField(
        # 管理画面での表示名
        verbose_name="役職",
        max_length=30,
        blank=True,
        null=True)
    department = models.CharField(
        # 管理画面での表示名
        verbose_name="所属部署",
        max_length=30,
        blank=True,
        null=True)
    delete_flag = models.IntegerField(
        # 管理画面での表示名
        verbose_name="削除フラグ",
        max_length=1,
        # 初期値
        default=0)
    registration_date = models.DateTimeField(
        # 管理画面での表示名
        verbose_name="登録日",
        # 初期値
        default=timezone.now())
    update_date = models.DateTimeField(
        # モデルインスタンスの度に現在時刻で更新
        auto_now=True)
    def __str__(self):
        return str(self.user_id)

# 貸出情報テーブル
class Device_history(models.Model):
    device_id = models.ForeignKey(
        Devices,
        on_delete=models.CASCADE,
        # 管理画面での表示名
        verbose_name="機器番号")
    user_id = models.ForeignKey(
        Users,
        on_delete=models.CASCADE,
        # 管理画面での表示名
        verbose_name="社員番号")
    rental_start = models.DateTimeField(
        # 管理画面での表示名
        verbose_name="貸出日")
    rental_limit = models.DateTimeField(
        # 管理画面での表示名
        verbose_name="返却予定日")
    rental_end = models.DateTimeField(
        # 管理画面での表示名
        verbose_name="返却日",
        blank=True,
        null=True)
    delete_flag = models.IntegerField(
        # 管理画面での表示名
        verbose_name="削除フラグ",
        # 初期値
        default=0)
    registration_date = models.DateTimeField(
        # 管理画面での表示名
        verbose_name="申請日",
        # 初期値
        default=timezone.now())
    update_date = models.DateTimeField(
        # モデルインスタンスの度に現在時刻で更新
        auto_now=True)
    def __str__(self):
        return str(self.user_id.user_id) +"_"+ str(self.device_id.device_id)

AssetsManager001/polls/views.py
from django.utils import timezone
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import TemplateView
from .models import Devices,Users,Device_history
from .forms import DevicesForm,UsersForm,DeviceHistoryAddForm,DeviceHistoryEditForm
from ._getState import classify_gender_for_Users
from ._getState import get_lend_column,get_devices_column,get_users_column
from ._getState import classify_status_use,classify_for_Devices



class MainView(TemplateView):
    template_name = 'main.html'



def lend(request):
    return lendSort(request,-1)



def lendSort(request,column_number):
    Sorts = {}
    if 0 <= column_number and column_number<100:
        column_str = get_lend_column(column_number//2)
        if column_number%2 ==0:
            lend_list = Device_history.objects.filter(rental_end=None).order_by(str('-'+column_str))
        else:
            lend_list = Device_history.objects.filter(rental_end=None).order_by(str(column_str))
        Sorts[str(column_str+str( (column_number % 2)+1 ))] = True
    elif 100<=column_number:
        if column_number//100 ==1:
            column_str = "status_use"
            (queryset1,queryset2,queryset3,_) = classify_status_use(table_name="Device_history")
            if column_number%100 == 1:
                lend_list = queryset1 | queryset2 | queryset3
            elif column_number%100 == 2:
                lend_list = queryset2 | queryset3 | queryset1
            elif column_number%100 == 3:
                lend_list = queryset3 | queryset1 | queryset2
        Sorts[str(column_str+str(column_number % 100))] = True
    else:
        lend_list = Device_history.objects.filter(rental_end=None)
    context = {'lend_list': lend_list,
               'today':timezone.now(),
               'Sorts': Sorts,
               'page_lend':True}
    return render(request, 'lend.html', context)



def lendDelete(request):
    status_use_list = request.POST.getlist("status_use")
    delete_list = [i.split('+')[1][:-1] for i in status_use_list if "返却済" in i]
    print(status_use_list)
    print(delete_list)
    Device_history.objects.filter(pk__in=delete_list,rental_end=None).update(rental_end=timezone.now())
    return redirect('polls:lend')



def devices(request):
    return devicesSort(request,-1)



def devicesSort(request,column_number):
    Sorts = {}
    if 0 <= column_number and column_number<100:
        column_str = get_devices_column(column_number//2)
        if column_number%2 ==0:
            device_list = Devices.objects.filter(delete_flag=0).order_by(str('-'+column_str))
        else:
            device_list = Devices.objects.filter(delete_flag=0).order_by(str(column_str))
        Sorts[str(column_str+str( (column_number % 2)+1 ))] = True
    elif 100<=column_number:
        if column_number//100 ==1:
            column_str = "status_use"
            (queryset1,queryset2,queryset3,queryset4) = classify_status_use(table_name="Devices")
            if column_number%100 == 1:
                device_list = queryset1 | queryset2 | queryset3 | queryset4
            elif column_number%100 == 2:
                device_list = queryset2 | queryset3 | queryset4 | queryset1
            elif column_number%100 == 3:
                device_list = queryset3 | queryset4 | queryset1 | queryset2
            elif column_number%100 == 4:
                device_list = queryset4 | queryset1 | queryset2 | queryset3
        elif column_number//100 ==2:
            column_str = "rental_start"
            (queryset1,queryset2) = classify_for_Devices(sort_rule=bool(column_number%100 == 1),column_str="rental_start")
            device_list = queryset1 | queryset2
        elif column_number//100 ==3:
            column_str = "rental_limit"
            (queryset1,queryset2) = classify_for_Devices(sort_rule=bool(column_number%100 == 1),column_str="rental_limit")
            device_list = queryset1 | queryset2
        Sorts[str(column_str+str(column_number % 100))] = True
    else:
        device_list = Devices.objects.all()
    addRentDateForDevices(device_list)
    context = {'device_list': device_list,
               'today':timezone.now(),
               'Sorts': Sorts,
               'page_devices':True}
    return render(request, 'devices.html', context)



def addRentDateForDevices(lists):
    for i,v in enumerate(lists):
        data = Device_history.objects.filter(device_id=v.id,rental_end=None).order_by('rental_start').first()
        if not data == None:
            tmp = lists[i].__dict__
            tmp["rental_start"] = data.rental_start
            tmp["rental_limit"] = data.rental_limit
            tmp["rental_end"] = data.rental_end



def devicesDelete(request):
    check = request.POST.getlist("delete")
    Devices.objects.filter(pk__in=check).update(delete_flag=1)
    return redirect('polls:devices')



def users(request):
    return usersSort(request,-1)



def usersSort(request,column_number):
    Sorts = {}
    if 0 <= column_number and column_number<100:
        column_str = get_users_column(column_number//2)
        if column_number%2 ==0:
            user_list = Users.objects.filter(delete_flag=0).order_by(str('-'+column_str))
        else:
            user_list = Users.objects.filter(delete_flag=0).order_by(str(column_str))
        Sorts[str(column_str+str( (column_number % 2)+1 ))] = True
    elif 100<=column_number:
        if column_number//100 ==1:
            column_str = "status_use"
            (queryset1,queryset2,queryset3,queryset4) = classify_status_use(table_name="Users")
            if column_number%100 == 1:
                user_list = queryset1 | queryset2 | queryset3 | queryset4
            elif column_number%100 == 2:
                user_list = queryset2 | queryset3 | queryset4 | queryset1
            elif column_number%100 == 3:
                user_list = queryset3 | queryset4 | queryset1 | queryset2
            elif column_number%100 == 4:
                user_list = queryset4 | queryset1 | queryset2 | queryset3
        elif column_number//100 ==2:
            column_str = "gender"
            (queryset1,queryset2,queryset3) = classify_gender_for_Users()
            if column_number%100 == 1:
                user_list = queryset2 | queryset3 | queryset1
            elif column_number%100 == 2:
                user_list = queryset3 | queryset2 | queryset1
            elif column_number%100 == 3:
                user_list = queryset1 | queryset2 | queryset3
        Sorts[str(column_str+str(column_number % 100))] = True
    else:
        user_list = Users.objects.all()
    addRentDateForUsers(user_list)
    context = {'user_list': user_list,
               'today':timezone.now(),
               'Sorts': Sorts,
               'page_users':True}
    return render(request, 'users.html', context)



def addRentDateForUsers(lists):
    for i,v in enumerate(lists):
        data = Device_history.objects.filter(user_id=v.id,rental_end=None).order_by('rental_start').first()
        if not data == None:
            tmp = lists[i].__dict__
            tmp["rental_start"] = data.rental_start
            tmp["rental_limit"] = data.rental_limit
            tmp["rental_end"] = data.rental_end



def usersDelete(request):
    check = request.POST.getlist("delete")
    Users.objects.filter(pk__in=check).update(delete_flag=1)
    return redirect('polls:users')



def lendAdd(request):
    params = {'title':'貸出情報入力',
              'button_name':'登録',
              'form': DeviceHistoryAddForm()}
    if request.method == 'POST':
        form = DeviceHistoryAddForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('polls:lend')
        else:
            form = DeviceHistoryAddForm(request.POST)
            params["form"] = form
    return render(request, 'lendEdit.html', params)



def lendEdit(request,pk):
    lend = get_object_or_404(Device_history, pk=pk)
    params = {'lend':lend,
              'title':'貸出情報入力',
              'button_name':'変更',
              'form': None}
    if request.method == 'POST':
        form = DeviceHistoryEditForm(request.POST,instance=lend)
        if form.is_valid():
            form.save()
            return redirect('polls:lend')
        else:
            params["form"] = form
    else:
        lend_initial = {
            'user_id': lend.user_id,
            'device_id': lend.device_id,
            'rental_start': lend.rental_start,
            'rental_limit': lend.rental_limit}
        params['form'] = DeviceHistoryEditForm(initial=lend_initial)
    return render(request, 'lendEdit.html', params)



def devicesEdit(request,pk):
    if not pk==0:
        device = get_object_or_404(Devices, pk=pk)
        params = {'device_':device,
                  'title':'機器情報入力',
                  'button_name':'変更',
                  'form': None}
        if request.method == 'POST':
            form = DevicesForm(request.POST,instance=device)
            if form.is_valid():
                form.save()
                return redirect('polls:devices')
            else:
                form = DevicesForm(request.POST)
                params["form"] = form
        else:
            params['form'] = DevicesForm(initial=device.__dict__)
    else:
        params = {'title':'機器情報入力',
                  'button_name':'登録',
                  'form': DevicesForm()}
        if request.method == 'POST':
            form = DevicesForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('polls:devices')
            else:
                form = DevicesForm(request.POST)
                params["form"] = form
    return render(request, 'devicesEdit.html', params)
 



AssetsManager001/polls/templates/devices.html
{% extends "main_.html" %}



{% block content %}
<h4>機器一覧</h4>
<form class="" action="{% url 'polls:devicesDelete' %}" method="post">
{% csrf_token %}
<div class="card-footer">
  <a href="{% url 'polls:devicesEdit' 0 %}" class="btn btn-primary">追加</a>
  <input type="submit" class="btn btn-danger" name="button" value="削除">
</div>

<table class="bordered table">
    <tr>
        <th></th>
        <th></th>
        <th>
            {% if Sorts.device_id1 %}
            <font color="red">機器番号</font>
            <a href="{% url 'polls:devicesSort' 1 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.device_id2 %}
            <font color="red">機器番号</font>
            <a href="{% url 'polls:devicesSort' 0 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            機器番号
            <a href="{% url 'polls:devicesSort' 0 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.maker1 %}
            <font color="red">メーカ</font>
            <a href="{% url 'polls:devicesSort' 3 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.maker2 %}
            <font color="red">メーカ</font>
            <a href="{% url 'polls:devicesSort' 2 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            メーカ
            <a href="{% url 'polls:devicesSort' 2 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.OS1 %}
            <font color="red">OS</font>
            <a href="{% url 'polls:devicesSort' 5 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.OS2 %}
            <font color="red">OS</font>
            <a href="{% url 'polls:devicesSort' 4 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            OS
            <a href="{% url 'polls:devicesSort' 4 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.memory1 %}
            <font color="red">メモリ</font>
            <a href="{% url 'polls:devicesSort' 7 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.memory2 %}
            <font color="red">メモリ</font>
            <a href="{% url 'polls:devicesSort' 6 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            メモリ
            <a href="{% url 'polls:devicesSort' 6 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.storage1 %}
            <font color="red">容量</font>
            <a href="{% url 'polls:devicesSort' 9 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.storage2 %}
            <font color="red">容量</font>
            <a href="{% url 'polls:devicesSort' 8 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            容量
            <a href="{% url 'polls:devicesSort' 8 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.CPU1 %}
            <font color="red">CPU</font>
            <a href="{% url 'polls:devicesSort' 11 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.CPU2 %}
            <font color="red">CPU</font>
            <a href="{% url 'polls:devicesSort' 10 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            CPU
            <a href="{% url 'polls:devicesSort' 10 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.GPU1 %}
            <font color="red">GPU</font>
            <a href="{% url 'polls:devicesSort' 13 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.GPU2 %}
            <font color="red">GPU</font>
            <a href="{% url 'polls:devicesSort' 12 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            GPU
            <a href="{% url 'polls:devicesSort' 12 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.inventory1 %}
            <font color="red">保管場所</font>
            <a href="{% url 'polls:devicesSort' 15 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.inventory2 %}
            <font color="red">保管場所</font>
            <a href="{% url 'polls:devicesSort' 14 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            保管場所
            <a href="{% url 'polls:devicesSort' 14 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.broken_flag1 %}
            <font color="red">故障</font>
            <a href="{% url 'polls:devicesSort' 17 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.broken_flag2 %}
            <font color="red">故障</font>
            <a href="{% url 'polls:devicesSort' 16 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            故障
            <a href="{% url 'polls:devicesSort' 16 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.rental_start1 %}
            <font color="red">貸出日</font>
            <a href="{% url 'polls:devicesSort' 202 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.rental_start2 %}
            <font color="red">貸出日</font>
            <a href="{% url 'polls:devicesSort' 201 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            貸出日
            <a href="{% url 'polls:devicesSort' 201 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.rental_limit1 %}
            <font color="red">返却予定日</font>
            <a href="{% url 'polls:devicesSort' 302 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.rental_limit2 %}
            <font color="red">返却予定日</font>
            <a href="{% url 'polls:devicesSort' 301 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            返却予定日
            <a href="{% url 'polls:devicesSort' 301 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            {% if Sorts.registration_date1 %}
            <font color="red">機器登録日</font>
            <a href="{% url 'polls:devicesSort' 19 %}"><ion-icon name="arrow-down-outline"></ion-icon></a>
            {% elif Sorts.registration_date2 %}
            <font color="red">機器登録日</font>
            <a href="{% url 'polls:devicesSort' 18 %}"><ion-icon name="arrow-up-outline"></ion-icon></a>
            {% else %}
            機器登録日
            <a href="{% url 'polls:devicesSort' 18 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>
            貸出状況
            {% if Sorts.status_use1 %}
            <a href="{% url 'polls:devicesSort' 102 %}"><font color="red">貸出予定</font></a>
            {% elif Sorts.status_use2 %}
            <a href="{% url 'polls:devicesSort' 103 %}"><font color="red">貸出中</font></a>
            {% elif Sorts.status_use3 %}
            <a href="{% url 'polls:devicesSort' 104 %}"><font color="red">貸出中（期限超過）</font></a>
            {% elif Sorts.status_use4 %}
            <a href="{% url 'polls:devicesSort' 101 %}"><font color="red">空</font></a>
            {% else %}
            <a href="{% url 'polls:devicesSort' 101 %}"><ion-icon name="swap-vertical-outline"></ion-icon></a>
            {% endif %}
        </th>
        <th>備考</th>
    </tr>
    {% if device_list %}
        {% for device in device_list %}
        {% if not device.delete_flag %}
            <tr>
                <td>
                    <label>
                    {% if not device.rental_start %}
                        <input type="checkbox" name="delete" value={{ device.id }}>
                    {% else %}
                        {% if device.rental_end %}
                            <input type="checkbox" name="delete" value={{ device.id }}>
                        {% else %}
                            <input type="checkbox" name="delete" value={{ device.id }} disabled="disabled">
                        {% endif %}
                    {% endif %}
                    </label>
                </td>
                <td>
                <a href="{% url 'polls:devicesEdit' device.id %}">
                    <p>編集</p>
                </a>
                </td>
                <td>{{ device.device_id }}</td>
                <td>
                {% if device.maker %}
                    {{ device.maker }}
                {% endif %}
                </td>
                <td>
                {% if device.OS %}
                    {{ device.OS }}
                {% endif %}
                </td>
                <td>
                {% if device.memory %}
                    {{ device.memory }}
                {% endif %}
                </td>
                <td>
                {% if device.storage %}
                    {{ device.storage }}
                {% endif %}
                </td>
                <td>
                {% if device.CPU %}
                    {{ device.CPU }}
                {% endif %}
                </td>
                <td>
                {% if device.GPU %}
                    {{ device.GPU }}
                {% endif %}
                </td>
                <td>{{ device.inventory }}</td>
                <td>{{ device.broken_flag }}</td>
                <td>{{ device.rental_start|date:"Y/n/j" }}</td>
                <td>{{ device.rental_limit|date:"Y/n/j" }}</td>
                <td>{{ device.registration_date|date:"Y/n/j" }}</td>
                <td>
                {% if not device.rental_start %}
                    空
                {% else %}
                    {% if device.rental_end %}
                        空
                    {% else %}
                        {% if device.rental_start >= today %}
                            貸出予定
                        {% else %}
                            {% if today <= device.rental_limit %}
                                貸出中
                            {% else %}
                                貸出中（期限超過）
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}
                </td>
                <td>{{ device.remarks }}</td>
            </tr>
        {% endif %}
        {% endfor %}
    {% else %}
         <td>存在しません</td>
    {% endif %}
</table>
</form>

{% endblock %}

AssetsManager001/polls/templates/devicesEdit.html
{% extends "main_.html" %}



{% block content %}
<center><h1>{{ title }}</h1></center>
{% if device_ %}
<form method="POST" action="{% url 'polls:devicesEdit' device_.id %}" class="form-horizontal">
{% else %}
<form method="POST" action="{% url 'polls:devicesEdit' 0 %}" class="form-horizontal">
    {% endif %}
    {% csrf_token %}
    <center>
        <div class="form-group">
            <table>
            {{ form.as_table }}
            </table>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-secondary">{{ button_name }}</button>
            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">キャンセル</a>
        </div>
    </center>
</form>

{% endblock %}

AssetsManager001/polls/templates/lendEdit.html
{% extends "main_.html" %}

{% block extra_head %}

{% endblock %}

{% block content %}
<center><h1>{{ title }}</h1></center>
{% if lend %}
<form method="POST" action="{% url 'polls:lendEdit' lend.id %}" class="form-horizontal">
{% else %}
<form method="POST" action="{% url 'polls:lendAdd' %}" class="form-horizontal">
    {% endif %}
    {% csrf_token %}
    <center>
        <ul>
            {% for error in form.non_field_errors %}
            {% endfor %}
        </ul>
        <div class="form-group">
            <table>
                {{ form_.media }}
                {{ form.as_table }}
            </table>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-secondary">{{ button_name }}</button>
            <a href="{% url 'polls:lend' %}" class="btn btn-secondary">キャンセル</a>
        </div>
    </center>
</form>



{% endblock %}